{
 "title": "api_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Successful generations (200 OK, endpoint \"/generate\")",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/generate\", status=\"2xx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful downloads (200 OK, endpoint \"/download/{file_id}\")",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/download/{file_id}\", status=\"2xx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unsuccessful generations (4xx error)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/generate\", status=\"4xx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unsuccessful generations (5xx error)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/generate\", status=\"5xx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unsuccessful downloads (4xx error)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/download/{file_id}\", status=\"4xx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage by API",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP request duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=\"/generate\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage per API",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP request duration (sec) - Metrics scrapping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=\"/metrics\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}