services:
  whisper:
    build:
      context: ./services/whisper-api
      dockerfile: Dockerfile
    image: whisper-api
    volumes:
      - ./services/whisper-api/models:/models
    expose:
      - "8035"
    hostname: whisperapi_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  tts:
    build:
      context: ./services/tts-api
      dockerfile: Dockerfile
    image: tts-api
    volumes:
      - ./services/tts-api/models:/models
    expose:
      - "8025"
    hostname: ttsapi_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  gemma:
    build:
      context: ./services/gemma-api
      dockerfile: Dockerfile
    image: gemma-api
    volumes:
      - ./services/gemma-api/models:/models
    expose:
      - "8005"
    hostname: gemmaapi_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  llama:
    build:
      context: ./services/llama-api
      dockerfile: Dockerfile
    image: llama-api
    volumes:
      - ./services/llama-api/models:/models
    expose:
      - "8012"
    hostname: llamaapi_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  stable-diff:
    build:
      context: ./services/stable-diffusion-api
      dockerfile: Dockerfile
    image: sd-api
    volumes:
      - ~/.cache/huggingface:/app/.cache/huggingface:ro
    expose:
      - "8015"
    hostname: sdapi_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - whisper
      - tts
      - gemma
      - llama
      - stable-diff

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "127.0.0.1:8090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    hostname: prometheus

  grafana:
    image: grafana/grafana
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:8034:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
