FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

RUN apt-get update && apt-get install -y git wget build-essential libgl1 libglib2.0-0 libxext6 libxrender-dev ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-base.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements-base.txt
